
package dev.ifrs.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Big", targetNamespace = "http://ws.ifrs.dev/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Big {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert2", targetNamespace = "http://ws.ifrs.dev/", className = "dev.ifrs.ws.Convert2")
    @ResponseWrapper(localName = "convert2Response", targetNamespace = "http://ws.ifrs.dev/", className = "dev.ifrs.ws.Convert2Response")
    public int convert2(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert1", targetNamespace = "http://ws.ifrs.dev/", className = "dev.ifrs.ws.Convert1")
    @ResponseWrapper(localName = "convert1Response", targetNamespace = "http://ws.ifrs.dev/", className = "dev.ifrs.ws.Convert1Response")
    public int convert1(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
